# Generated by Django 5.2.1 on 2025-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
