# Generated by Django 5.2.1 on 2025-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_appvarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvarity',
            name='pricing',
            field=models.CharField(default='0', max_length=45),
        ),
    ]
