# Generated by Django 5.2.1 on 2025-05-21 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_appreview_appverification_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('buying', models.CharField(default='0', max_length=45)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buying', to='app1.appvarity')),
            ],
        ),
    ]
